twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig
    globals:
        recipeRepository: "@App\\Repository\\RecipeRepository"
        recipeTypeRepository: "@App\\Repository\\RecipeTypeRepository"
        ingredientRepository: "@App\\Repository\\IngredientRepository"
        departmentRepository: "@App\\Repository\\DepartmentRepository"
        shoppingListRepository: "@App\\Repository\\ShoppingListRepository"
        shoppingListRowRepository: "@App\\Repository\\ShoppingListRowRepository"
        javascripts_dir: '/js/'

when@test:
    twig:
        strict_variables: true
