<?php

namespace App\DataFixtures;


class UserFixture
{
    const USERS = [
        [
            "email" => "alexiane.sichi@gmail.com",
            "roles" => [],
            "password" => "test",
            "fullname" => "Alexiane Sichi",
            "recipes" => [
                "pates carbonara",
                "fajitas",
                "œufs à la coque",
                "burger",
                "tarte tatin",
                "ramen",
                "salade caesar",
                "gaspacho",
                "poulet thai",
                "gnocci",
                "salade composée",
                "raviole",
                "sauce lentille",
                "blé dinde",
                "potage",
                "gratin de pate",
                "gratin de choux fleur",
                "gratin courgette",
                "lasagne",
                "quenelle",
                "crumble de courgette",
                "pizza",
                "pizza big apple",
                "baggle",
                "woke",
                "riz cantonais",
                "tomate farcie",
                "omelette",
                "œuf dur",
                "chili con carne",
                "panini",
                "tartine",
                "crepe",
                "galette bretonne",
                "croque monsieur",
                "brique",
                "raclette",
                "fondue",
                "soupe",
                "endive au jambon",
                "wrap",
                "tartare",
                "terrine aubergine",
                "taboulet syrien",
                "poulet basquaise",
                "tarte mozza",
                "moussaka",
                "tourte épinard",
                "tartiflette",
                "flamenkuche",
                "blanquette de veau",
                "bœuf bourguignon",
                "poulet indien",
                "pate bolognaise",
                "pate pesto",
                "saucisse purée",
                "petit pois poisson",
                "nuggets fritte",
                "légume cordon bleu",
                "risotto",
                "saumon papillotte",
                "tarte au pomme",
                "charlotte framboise",
                "moelleux chocolat",
                "gateau yaourt",
                "cookies",
                "muffin pépitte chocolat",
                "bananabread",
                "sablé",
                "marbré",
                "tiramisu citron",
            ]
        ],
        [
            "email" => "kantincharignon@gmail.com",
            "roles" => ["ROLE_ADMIN"],
            "password" => "test",
            "fullname" => "Kantin C.",
            "recipes" => []
        ],
    ];
}
